@ECHO OFF
CALL W#EXCHG.BAT
SET AD_SERVER_NAME=%W#EXCHG1%
SET DOMAIN_ADMIN_ACCOUNT=%W#EXCHG2%
SET ORGANIZATION=%W#EXCHG3%
SET ADMINISTRATIVE_GROUP=%W#EXCHG4%
SET MAILBOX=%W#EXCHG5%

cscript exch.vbs %COMPUTERNAME% "%ORGANIZATION%" "%ADMINISTRATIVE_GROUP%" %MAILBOX%
